Feature/eit 2027
enchainte/enchainte-sdk-kotlin pull request #2
Opened 2022-04-26 13:26 UTC by Neifi

Implement write and read JSON metadata in Java

2022-04-26 13:48 UTC, marcbaque requested changes

2022-04-26 13:48 UTC, marcbaque commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +                proof = fetchProof()
Doesn't this call need to await?

2022-04-26 13:48 UTC, marcbaque commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +    protected var signatures: Signatures? = Signatures(mutableListOf())
Should be initialized to null. Otherwise may lead to errors when comparing if a signature exists

2022-04-26 13:48 UTC, marcbaque commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +        return mapOf(Pair("signatures", metadata.signatures))?.let { this.buildFile(it) }
The proof isn't added to the output. Also, it isn't loaded in the metadata initializer (L70).

2022-04-26 13:48 UTC, marcbaque commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +    override fun equals(other: Any?): Boolean {
Why are the equals and hashCode functions needed?

2022-04-26 13:48 UTC, marcbaque commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +    val propName: Map<String, Any>
Change the name to "other", for example. propName is a specific naming from Javascript

2022-04-26 13:48 UTC, marcbaque commented on src/test/kotlin/com/bloock/sdk/record/entity/document/JsonDocumentTest.kt
> +        val expectedContent = """{"hello":"world"}""".trimMargin()
Maybe use JSON_CONTENT variable instead?

2022-04-26 13:48 UTC, marcbaque commented on src/test/kotlin/com/bloock/sdk/record/entity/document/JsonDocumentTest.kt
> +            val docProof = file.getDocPayload()
It should be getDocProof, same in L54

2022-04-26 13:48 UTC, marcbaque commented on src/test/kotlin/com/bloock/sdk/record/entity/document/JsonDocumentTest.kt
> +            val docProof = file.getDocPayload()
It should be getDocProof, same in L76

2022-04-26 13:48 UTC, marcbaque commented on src/test/kotlin/com/bloock/sdk/record/entity/document/JsonDocumentTest.kt
> +            file.addSignature(proof)
addSignatures should not take both signature and proof. It must be separated into two functions (addSignatures and setProof)

2022-04-27 12:12 UTC, Neifi commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +    override fun equals(other: Any?): Boolean {
Now I use the domain entity, it was a mistake I think

2022-04-27 12:18 UTC, Neifi commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +                proof = fetchProof()
Yes, I changed the behaviour now

2022-04-27 13:39 UTC, marcbaque requested changes

2022-04-27 13:39 UTC, marcbaque commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +    fun getDocProf() = this.proof
It's getDocProof

2022-04-27 13:39 UTC, marcbaque commented on src/main/kotlin/com/bloock/sdk/record/entity/document/Document.kt
> +    var ready: Unit
I think you don't need the ready parameter in Java/Kotlin as you are treating everything synchronously (runBlocking), so you can remove it.

2022-05-05 13:17 UTC, closed without merging